services: 
  Shared.QueryHandlersInformation:
    class: contexts/shared/infrastructure/QueryHandlersInformation
    arguments: ['!tagged queryHandler']
 
  Shared.QueryBus:
    class: contexts/shared/infrastructure/InMemoryQueryBus
    arguments: ['@Shared.QueryHandlersInformation']