services: 
  Shared.QueryHandlersInformation:
    class: contexts/shared/infrastructure/QueryHandlersInformation
    arguments: ['!tagged queryHandler']
 
  Shared.QueryBus:
    class: contexts/shared/infrastructure/InMemoryQueryBus
    arguments: ['@Shared.QueryHandlersInformation']

  Shared.CommandHandlersInformation:
    class: contexts/shared/infrastructure/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.CommandBus:
    class: contexts/shared/infrastructure/InMemoryCommandBus
    arguments: ['@Shared.CommandHandlersInformation']